name: 'release'
on:
  push:
    branches:
      - main
      - release

env:
  node_version: 18.11.0

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run check

  format:
    needs: static-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci
      - run: npm run format
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "formatter[bot]@users.noreply.github.com"
          git config --local user.name "formatter[bot]"
          git commit -am "chore: format code"
          git push

  test:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci
      - run: npm run coverage
      - name: integration test
        run: npm run test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci
      - run: npm run build:node
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      # TODO: use github hooks to pull this artifact to own server
